config/routes.rb
Rails.application.routes.draw do

  get '/'         => 'gigs#home'
  # get '/sidebar'  => 'gigs#sidebar'
  get 'search'    => 'gigs#search'

  resources :gigs do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :gig
end

app/models/gig.rb
class Gig < ActiveRecord::Base

	has_many :comments

	validates :venue  , presence: true
	validates :price  , presence: true
	validates :price  ,	numericality: true
	validates :date   , presence: true
	validates :city   , presence: true
	validates :artist , presence: true
	
	# validates :city, 		format: { with: /\A[a-zA-Z]+\z/, 	message: "only allows letters" }
	# validates :venue,		format: { with: /\A[a-zA-Z0-9]+\z/, message: "only allows letters" }
	# validates :artist, 		format: { with: /\A[a-zA-Z0-9]+\z/, message: "only allows letters" }
	# validates :description,	format: { with: /\A[a-zA-Z0-9]+\z/, message: "only allows letters" }

	# validates :date_cannot_be_in_the_past 	, true

	def date_cannot_be_in_the_past
    	if date.present? && date < Date.today
      		errors.add(:date, "can't be in the past")
   		end
	end

##########################################
#
# 	C L A S S
#
##########################################

	def self.get_all(limit)
		order('date ASC').limit(limit)
	end

	def self.get_in_range(start_time, end_time)
		where("date > ?", start_time.beginning_of_day).where("date < ?", end_time.end_of_day).order('date ASC')
	end

	def self.get_one(id)
		find_by(id: id)
	end

	def self.search(query)
		query = query.downcase
		result = where("LOWER(artist) LIKE '%#{query}%' OR LOWER(venue) LIKE '%#{query}%' OR LOWER(city) LIKE '%#{query}%'")
#		get_by_rating(result)
		result
	end

	def self.get_by_rating(entries)
		entries.sort {|x,y| y.avg_rating <=> x.avg_rating}
	end

##########################################
#
#  	I N S T A N C E
#
##########################################

	def avg_rating
		count = reviews.count
		count > 0 ? '%.2f' % (reviews.reduce(0) {|sum,x| sum + x.rating }.to_f / count) : '0.00'
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception

	before_action :sidebar

	private def sidebar
		start_time	= Time.new
		end_time  	= start_time + 1.month
		@gigs_month = Gig.get_in_range(start_time, end_time)
	end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def index
		@gig 		= Gig.find params[:gig_id]
		@comments 	= @gig.comments
	end

	def show
		@gig 		= Gig.find params[:gig_id]
		@comment 	= @gig.comments.find params[:id]
	end	

	def new
		@gig 		= Gig.find params[:gig_id]
		@comment 	= @gig.comments.new
	end

	def create
		@gig 		= Gig.find params[:gig_id]
		@comment 	= @gig.comments.new comment_params

		if @comment.save
			redirect_to action: 'show', controller: 'gigs', gig_id: @gig.id, notice: "New comment added"
		else 
			flash[:alert] = "Failed!"
			render 'new'
		end
	end

	def edit
		@gig 		= Gig.find params[:gig_id]
		@comment 	= @gig.comments.find params[:id]
	end

	def update
		@gig 		= Gig.find params[:gig_id]
		@comment 	= @gig.comments.find params[:id]

		if @comment.update_attributes comment_params
			redirect_to action: 'show', controller: 'gigs', gig_id: @gig.id, notice: "Comment updated"
		else 
			flash[:alert] = "Failed!"
			render 'edit'
		end
	end

	def destroy
		@gig 		= Gig.find params[:gig_id]
		@comment 	= @gig.comments.find params[:id]

		if @comment.destroy 
			redirect_to action: 'show', controller: 'gigs', gig_id: @gig.id
		else 
			flash[:alert] = "Failed!"
  		end
	end


	private

	def comment_params
		params.require(:comment).permit(:title, :content, :rating)
	end

end

app/controllers/gigs_controller.rb
require 'time'

class GigsController < ApplicationController

	def home
		start_time	= Time.new
		end_time  	= start_time + 1.week
		@gigs 		= Gig.get_in_range(start_time, end_time)
	end

	def index
		@list_length = 20
		@gigs 		 = Gig.get_all(@list_length)
		if @gigs.count < @list_length
			@list_length = @gigs.count
		end
	end

	def show
		@gig 	= Gig.find params[:id]
	end	

	def new
		@gig 	= Gig.new
	end

	def create
		@gig 	= Gig.new gig_params

		if @gig.save
			redirect_to action: 'index', controller: 'gigs', notice: "New Gig added"
		else 
			render 'new', alert: "Failed!"
		end
	end

	def edit
		@gig 	= Gig.find params[:id]
	end

	def update
		@gig 	= Gig.find params[:id]

		if @gig.update_attributes gig_params
			redirect_to action: 'index', controller: 'gigs'
		else 
			flash[:alert] = "Failed!"
			render 'edit'
		end
	end

	def destroy
		@gig 	= Gig.find params[:id]

		if @gig.destroy 
			redirect_to action: 'index', controller: 'gigs'
		else 
			flash[:alert] = "Failed!"
  		end
	end

	def search
		@query = params[:query]
		@gigs = Gig.search(@query)
		render 'search'
	end


	private

	def gig_params
		params.require(:gig).permit(:venue, :city, :price, :description, :date, :artist)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/views/comments/_form.html.erb
<% if flash[:notice] %>
<%= flash[:notice] %>
<% end %>

<% if @gig.errors.any? %>
<ul>
	<% @gig.errors.full_messages.each do |msg| %>
	<li style="color:red"><%= msg%></li>
	<% end %>
</ul>
<% end %>

<%= form_for [@gig, @comment] do |f| %>
	<table class="table--add">
		<tr>
			<td><%= f.label :title %></td>
			<td><%= f.text_field :title %></td>
		</tr>
		<tr>
			<td><%= f.label :rating %></td>
			<td><%= f.text_field :rating %></td>
		</tr>
		<tr>
			<td><%= f.label :content %></td>
			<td><%= f.text_area :content %></td>
		</tr>
	</table>
	<%= f.submit 'Save' %>
	<%= link_to('Cancel', gig_path(@gig)) %>
<% end %>
<br>

<% %>

app/views/comments/_searchbar.html.erb
<!-- searchbar -->
<!-- <div class="input-group searchbar">
	<form action="/search" class="seach-form">
		<input id="searchbar" type="text" name="query" class="form-control" placeholder="Search for...">
		<span class="input-group-btn">
			<button class="btn btn-default" type="button">Search</button>
		</span>
	</form>
</div> 
 -->
<br>
<form action="/search" class="seach-form">
	<input type="text" placeholder="search by artist or venue" name="query"> 
	<button type="submit">Search</button> 
</form>

app/views/comments/_sidebar.html.erb
<h3>concerts next month:</h3>

<ul>
	<% @gigs_month.each do |g|  %>
		<li>
			<%= "#{g.artist}" %><br>
			at <%= link_to(g.venue, gig_path(g)) %> <br>
			on <%= g.date.strftime('%Y-%b-%e') %><br>
			in <%= "#{g.city}" %><br>
		</li>
	<% end %>
</ul>

app/views/comments/_table.html.erb
<table>
	<tr class="index__tr">
		<th>Artist</th>
		<th>Venue</th>
		<th>Date</th>
		<th>Description</th>
		<th>City</th>
		<th>Price</th>
	</tr>

	<% @gigs.each do |g|  %>
		<tr class="index__tr">
			<td><%= link_to(g.artist, gig_path(g)) %></td>
			<td><%= "#{g.venue}" %> </td>
			<td><%= "#{g.date}" %></td>
 			<td><%= "#{g.description}" %></td>
			<td><%= "#{g.city}" %></td>
			<td>$<%= "#{'%.2f' % g.price}" %></td>
		</tr>
	<% end %>
</table>

app/views/comments/edit.html.erb
<%= render 'form' %>

app/views/comments/home.html.erb
<%= render 'searchbar' %>

<h3>concerts next 7 days:</h3>
<br>

<%= render 'table' %>

<%= link_to('All concerts' , gigs_path) %> 

app/views/comments/index.html.erb
<%= render 'searchbar' %>

<h3>The <%= @list_length %> next concerts:</h3>
<br>

<%= render 'table' %>

<%= link_to('Add concert' , new_gig_path) %> 

<!-- <form>
	<input id="prodName"  type="text" placeholder="Enter product name" name="name"> 
	<input id="prodDesc"  type="text" placeholder="Description" name="description"> 
	<input id="prodPrice" type="text" placeholder="Price" name="price"> 
	<button id="prodSubmit" type="submit" name="price">Add Book</button> 
</form>
 -->

app/views/comments/new.html.erb
<%= render 'form' %>

app/views/comments/search.html.erb
<h3>I found <%= @gigs.count %> concerts that match your query '<%= @query %>':</h3>

<%= render 'table' %>

<%= link_to('Back' , gigs_path) %> 

app/views/comments/show.html.erb
<h2><%= @gig.artist %></h2>
<p>At <%= @gig.venue %></p>
<p>on <%= @gig.date.strftime('%a %b %e %Y') %></p>
<p>for only <%= '%.2f' % @gig.price %>$</p>
<p>in <%= @gig.city %></p>
<p><%= @gig.description %></p>



<%= link_to('Back', gigs_path) %>
<%  %>

app/views/gigs/_form.html.erb
<% if flash[:notice] %>
<%= flash[:notice] %>
<% end %>

<% if @gig.errors.any? %>
<ul>
	<% @gig.errors.full_messages.each do |msg| %>
	<li style="color:red"><%= msg%></li>
	<% end %>
</ul>
<% end %>

<%= form_for [@gig] do |f| %>
	<table class="table--add">
		<tr>
			<td><%= f.label :artist %></td>
			<td><%= f.text_field :artist %></td>
		</tr>
		<tr>
			<td><%= f.label :venue %></td>
			<td><%= f.text_field :venue %></td>
		</tr>
		<tr>
			<td><%= f.label :date %></td>
			<td><%= f.date_field :date %></td>
		</tr>
		<tr>
			<td><%= f.label :city %></td>
			<td><%= f.text_field :city %></td>
		</tr>	
		<tr>
			<td><%= f.label :description %></td>
			<td><%= f.text_area :description %></td>
		</tr>
		<tr>
			<td><%= f.label :price %></td>
			<td><%= f.text_field :price %></td>
		</tr>
	</table>
	<%= f.submit 'Save' %>
	<%= link_to('Cancel', gigs_path) %>
<% end %>
<br>

<% %>

app/views/gigs/_searchbar.html.erb
<!-- searchbar -->
<!-- <div class="input-group searchbar">
	<form action="/search" class="seach-form">
		<input id="searchbar" type="text" name="query" class="form-control" placeholder="Search for...">
		<span class="input-group-btn">
			<button class="btn btn-default" type="button">Search</button>
		</span>
	</form>
</div> 
 -->
<br>
<form action="/search" class="seach-form">
	<input type="text" placeholder="search by artist, venue or location" name="query"> 
	<button type="submit">Search</button> 
</form>

app/views/gigs/_sidebar.html.erb
<h3>Concerts next month:</h3>

<ul>
	<% @gigs_month.each do |g|  %>
		<li class="sidebar__li">
			<%= g.date.strftime('%Y-%b-%e') %><br>
			<%= link_to(g.artist, gig_path(g)) %><br>
			at <%= g.venue %> in <%= "#{g.city}" %>
		</li>
	<% end %>
</ul>

app/views/gigs/_table.html.erb
<table>
	<tr class="index__tr">
		<th>Artist</th>
		<th>Venue</th>
		<th>Date</th>
		<th>Description</th>
		<th>City</th>
		<th>Price</th>
	</tr>

	<% @gigs.each do |g|  %>
		<tr class="index__tr">
			<td><%= "#{g.artist}" %></td>
			<td><%= link_to(g.venue, gig_path(g)) %> </td>
			<td><%= "#{g.date}" %></td>
 			<td><%= "#{g.description}" %></td>
			<td><%= "#{g.city}" %></td>
			<td>$<%= "#{'%.2f' % g.price}" %></td>
		</tr>
	<% end %>
</table>

app/views/gigs/home.html.erb
<%= render 'searchbar' %>

<h3>concerts next 7 days:</h3>
<br>

<%= render 'table' %>
<br>
<%= link_to('Show all concerts' , gigs_path) %> 

app/views/gigs/index.html.erb
<%= render 'searchbar' %>

<h3>The <%= @list_length %> next concerts:</h3>
<br>

<%= render 'table' %>
<br>
<%= link_to('Add concert' , new_gig_path) %> 

<!-- <form>
	<input id="prodName"  type="text" placeholder="Enter product name" name="name"> 
	<input id="prodDesc"  type="text" placeholder="Description" name="description"> 
	<input id="prodPrice" type="text" placeholder="Price" name="price"> 
	<button id="prodSubmit" type="submit" name="price">Add Book</button> 
</form>
 -->

app/views/gigs/show.html.erb
<h2><%= @gig.artist %></h2>
<p>At <%= @gig.venue %></p>
<p>on <%= @gig.date.strftime('%a %b %e %Y') %></p>
<p>for only <%= '%.2f' % @gig.price %>$</p>
<p>in <%= @gig.city %></p>
<p><%= @gig.description %></p>
<div class="hline"></div>

<% if @gig.comments.count > 0 %>
	<h4>Comments <%= link_to('Add your own comment', new_gig_comment_path(@gig)) %></h4>
	<br>
	<ul>
		<% @gig.comments.each do |c| %>
			<li class="comment__li">
				<div class="comment--title"><%= "#{c.title}" %></div>
				<div class="font--grey">Added: <%= "#{c.created_at}" %></div>
				<div class="font--grey">Rating: <%= "#{c.rating}" %></div>
				<div><%= "#{c.content}" %></div>
			</li>
		<% end %>
	</ul>

	<div class="hline"></div>

<% end %>

<%= link_to('Back', gigs_path) %>
<%  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Concerts</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Latest compiled and minified CSS -->

	<!-- <link rel="stylesheet" href="../../../../font-awesome-4.3.0/css/font-awesome.min.css"> -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

</head>
<body>
	<div class="container">

		<div class="row">
			<div class="header">
				<h1>Awesome concerts here!!!</h1>
				<div class="col-sm-3">
					<a href="/" class="home--link">Home</a>
				</div>
			</div>
		</div>

		<div class="row">

			<div class="col-sm-3 sidebar">

				<%= render 'gigs/sidebar' %>

			</div>

			<div class="col-sm-9 main">

				<%= yield %>

			</div>

		</div>
	</div>

	<div class="footer">
		<p>Copyright 2015 by Ironhackers</p>
	</div>

</body>
</html>